version: "3"

services:

  fpsandbox:
    image: geerlingguy/drupal-vm
    container_name: fpsandbox
    ports:
      - 8080:80
      - 443:443
    privileged: true
    volumes:
      - ./drupal:/var/www/drupalvm/drupal/web/:rw,delegated
      - ./foundation_patterns/:/var/www/drupalvm/drupal/web/themes/foundation_patterns/:rw,delegated
      - ./foundation_patterns_config/:/var/www/drupalvm/drupal/web/modules/custom/foundation_patterns_config/:rw,delegated
      - /var/lib/mysql
    command: /lib/systemd/systemd
